### ISSUE TITLE
monsoon umbrellas hackerrank problem

### ISSUE THREAD

**Issue by Poonamjo** [ubbn/HackerRank#1]
Can anyone please help me with the logic of this problem

**Comment by aprajitakain** [comment]
[Python_Monsoon_Umbrella.txt](https://github.com/ubbn/hacker-rank-solutions/files/2184003/Python_Monsoon_Umbrella.txt)

**Comment by dk103** [comment]
private static int getCombination(int n, int[] p) {
	    int result=-1;
	    int count=0;
	    Arrays.sort(p);
		for(int i=p.length-1;i>=0;i--) {
			count=count+p[i];
			int currentVal=0;
			if(p[i]==n) {
				result=1;
				break;
			}
			else {
				if(n>p[i]) {
					if(n%p[i]==0) {
						
						currentVal=n/p[i];
						
					}
					
					else {
						int compute= n/p[i];
						
					
						
						int itr=compute;
						while(itr>=1) {
							
							int rem=n-itr*p[i];
							 int sum2=itr*p[i];
							 boolean flag=false;
							 int inc=0;
							for(int k=i-1;k>=0;k--) {
								
								if(rem==p[k] ) {
									
									currentVal=itr+1;
									flag=true;
									break;
								
								}
								else if(rem%p[k]==0) {
									currentVal=itr+(rem/p[k]);
									flag=true;
									break;
									
								}
								else {
									sum2=sum2+p[k];
									if(sum2>n) {
									  break;
									}
									 inc++;
									if(sum2==n) {
										currentVal=itr+inc;
										flag=true;
									}
								}
							}								
							
							 if(result==-1 && flag==true) {
								 result =currentVal;
							 }
							 else if(result>currentVal && currentVal!=0) {
								 result =currentVal;
							 }
							 itr--;
						}
						
						
						
						 
					}
					 
					
					 
				}
			}
			  
			  if(result==-1 && currentVal!=0) {
				  result=currentVal;
			  }
			  else if(result!=-1 &&  currentVal !=0 && result>=currentVal)
					result=currentVal;
			  
			 
		}
		
			  if(count==n && result==-1) {
				  result=p.length; 
			  
		  }
		return result;
	
	
	}

**Comment by esjayrockz** [comment]
Why do you need to sort it?

**Comment by santosh-m** [comment]
I guess solution to this problem is similar to Classical Coin Changing problem. 
Refer below - 
https://github.com/mission-peace/interview/blob/master/src/com/interview/dynamic/CoinChangingMinimumCoin.java

**Comment by AhmedGamalFawzy** [comment]
[moonson-umbrellas.txt](https://github.com/user-attachments/files/16194284/moonson-umbrellas.txt)
Using javascript
